database:
  psql:
    type: psql
    host: localhost
    port: 5432
    user: template
    password: password
    name: postgres
    sslmode: disable
server:
  host: 127.0.0.1
  port: 10000
  debug: true
settings:
  timeframe: 14400
message_broker:
  kafka:
    host: localhost
    port: 9092
