// Code generated by SQLBoiler 4.10.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accounts       string
	CandlesContent string
	Contents       string
	Strategy       string
}{
	Accounts:       "accounts",
	CandlesContent: "candles_content",
	Contents:       "contents",
	Strategy:       "strategy",
}
